# Generated by Django 4.2.6 on 2025-01-16 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Kombi Markaları', 'verbose_name_plural': 'Kombi Markaları'},
        ),
        migrations.AddField(
            model_name='brand',
            name='service_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Yetkili Servis E-postası'),
        ),
    ]
