# Generated by Django 4.2.6 on 2025-01-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycontact',
            name='logo',
            field=models.ImageField(blank=True, default='company_logos/default_logo.png', null=True, upload_to='company_logos/', verbose_name='Firma Logosu'),
        ),
    ]
