"""
Django settings for techservice project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from os import getenv
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ga!^c2x!0%@mkd#3%404_kt--d85ddlkvub6cry6xx^f3w+ch1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

#SECRET_KEY = getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = getenv("IS_DEVELOPMENT",True)

#ALLOWED_HOSTS = [
    #getenv("APP_HOST")
#]



# Application definition

INSTALLED_APPS = [
    'jazzmin',  # En üstte olmalı
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mainapp',
    'widget_tweaks',
    'ckeditor',
]

JAZZMIN_SETTINGS = {
    # Başlık
    "site_title": "Teknik Servis Admin",
    "site_header": "Teknik Servis Yönetim Paneli",
    "site_brand": "Teknik Servis",
    "welcome_sign": "Teknik Servis Yönetim Paneline Hoşgeldiniz",

    # Renk teması
    "site_logo": 'images/indir.png',  # Logo eklemek isterseniz static dosya yolunu belirtin
    "theme": "default",
    "dark_mode_theme": "darkly",

    # Üst menü
    "topmenu_links": [
        {"name": "Ana Sayfa", "url": "admin:index"},
        {"name": "Site'yi Görüntüle", "url": "/", "new_window": True},
    ],

    # Sol menü
    "order_with_respect_to": [
        "mainapp.Service",
        "mainapp.Customer",
        "mainapp.ServiceRequest",
        "mainapp.CompanyContact",
        "mainapp.Brand",
        "mainapp.BoilerModel",
        "mainapp.ErrorCode",
        "mainapp.FAQ",
        "mainapp.VideoContent",
        "mainapp.BlogPost",
        "mainapp.Region",

    ],

    # Model grupları
    "icons": {
        "mainapp.Service": "fas fa-cogs",  # Hizmetler
        "mainapp.Customer": "fas fa-users",  # Müşteriler
        "mainapp.ServiceRequest": "fas fa-clipboard-list",  # Servis Talepleri
        "mainapp.CompanyContact": "fas fa-address-book",  # Şirket İletişim
        "mainapp.Brand": "fas fa-tags",  # Marka
        "mainapp.BoilerModel": "fas fa-industry",  # Kazan Modelleri
        "mainapp.ErrorCode": "fas fa-exclamation-triangle",  # Hata Kodu
        "mainapp.FAQ": "fas fa-question-circle",  # Sıkça Sorulan Sorular
        "mainapp.VideoContent": "fas fa-video",  # Video İçeriği
        "mainapp.BlogPost": "fas fa-blog",  # Blog Yazıları
        "mainapp.Region": "fas fa-location",  # Blog Yazıları
    },

    # Özel CSS
    "custom_css": None,
    "custom_js": None,

    # Diğer özelleştirmeler
    "show_ui_builder": True,
    "changeform_format": "horizontal_tabs",
    "language_chooser": True,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-white",
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-light-teal",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": True,
    "theme": "cosmo",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },
    "actions_sticky_top": False
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
]

ROOT_URLCONF = 'techservice.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Bu satırı ekleyin
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'mainapp.views.contact_info',  # Buraya ekleyin
            ],
        },
    },
]

WSGI_APPLICATION = 'techservice.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

# Desteklenen diller
LANGUAGES = [
    ('tr', 'Turkish'),
    ('en', 'English'),
]

# Varsayılan dil
LANGUAGE_CODE = 'tr'

TIME_ZONE = 'Europe/Istanbul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_ROOT=BASE_DIR/"staticfiles"

STATIC_URL = 'static/'

MEDIA_URL="media/"

MEDIA_ROOT=BASE_DIR/ "media"

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'ulasgultekin6278@gmail.com'
EMAIL_HOST_PASSWORD = 'jtgq rqbk qzxb ijiz'


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
